import './globals.css';
import type { Metadata } from 'next';
import TransitionWrapper from './transition-wrapper';

import { Schibsted_Grotesk } from 'next/font/google';

const fontSans = Schibsted_Grotesk({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable}`}>
        <TransitionWrapper>{children}</TransitionWrapper>
      </body>
    </html>
  );
}
