import './globals.css';
import type { Metadata } from 'next';

import { Schibsted_Grotesk } from 'next/font/google';
import Link from 'next/link';
import { ReactNode } from 'react';

const fontSans = Schibsted_Grotesk({
  subsets: ['latin'],
  weight: ['400', '600', '800'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function NavItem({ href, children }: { href: string; children: ReactNode }) {
  return (
    <li className="inline-block">
      <Link href={href} className="px-4 py-2">
        {children}
      </Link>
    </li>
  );
}

const pages = [
  { href: '/about', name: 'About' },
  { href: '/', name: 'Projects' },
  { href: '/portfolio', name: 'Portfolio' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${fontSans.variable}`}>
      <body className="container mx-auto min-h-screen py-14">
        <nav className="space-y-4">
          <h1 className="text-4xl font-bold tracking-tight">Thomas Shaw</h1>
          <ul className="-ml-4">
            <NavItem href="/about">About</NavItem>
            <NavItem href="/">Projects</NavItem>
            <NavItem href="/portfolio">Portfolio</NavItem>
          </ul>
        </nav>
        <div className="mt-12">{children}</div>
      </body>
    </html>
  );
}
